/*INSERT INTO EMOJIS (EMOJI) VALUES('nicom')
INSERT INTO EMOJIS (EMOJI) VALUES('notnicom')
INSERT INTO EMOJIS (EMOJI) VALUES('tomho')
INSERT INTO EMOJIS (EMOJI) VALUES('eggplant')

INSERT INTO USERS (`NAME`) VALUES('maikel');
INSERT INTO USERS (`NAME`) VALUES('nicor');
INSERT INTO USERS (`NAME`) VALUES('stefaan.vangoubergen');
INSERT INTO USERS (`NAME`) VALUES('nicom');
INSERT INTO USERS (`NAME`) VALUES('tomho');
INSERT INTO USERS (`NAME`) VALUES('kristof');
INSERT INTO USERS (`NAME`) VALUES('slackbot');
;
INSERT INTO WORDS (word) VALUES('fuck');
INSERT INTO "WORDS" VALUES('godverdomme');
INSERT INTO "WORDS" VALUES('lol');
INSERT INTO "WORDS" VALUES('ffs');
INSERT INTO "WORDS" VALUES('mondje');
INSERT INTO "WORDS" VALUES('retard');
INSERT INTO "WORDS" VALUES('soepke');
INSERT INTO "WORDS" VALUES('brol');
INSERT INTO "WORDS" VALUES('kut');
INSERT INTO "WORDS" VALUES('wtf');
INSERT INTO "WORDS" VALUES('nigga');
INSERT INTO "WORDS" VALUES('noob');
INSERT INTO "WORDS" VALUES('pomp');
INSERT INTO "WORDS" VALUES('fgt');
INSERT INTO "WORDS" VALUES('sow');
INSERT INTO "WORDS" VALUES('suicide');
INSERT INTO "WORDS" VALUES('punani');
INSERT INTO "WORDS" VALUES('bitch');
INSERT INTO "WORDS" VALUES('hennig');
INSERT INTO "WORDS" VALUES('klote');
INSERT INTO "WORDS" VALUES('janet');
INSERT INTO "WORDS" VALUES('homo');
INSERT INTO "WORDS" VALUES('flikker');
INSERT INTO "WORDS" VALUES('pab');
INSERT INTO "WORDS" VALUES('cunt');
INSERT INTO "WORDS" VALUES('tits');
INSERT INTO "WORDS" VALUES('hoer');
INSERT INTO "WORDS" VALUES('rekt');
INSERT INTO "WORDS" VALUES('anus');
INSERT INTO "WORDS" VALUES('zuk');
INSERT INTO "WORDS" VALUES('sodeju');
INSERT INTO "WORDS" VALUES('fock');
INSERT INTO "WORDS" VALUES('nalu');
INSERT INTO "WORDS" VALUES('nicom');
INSERT INTO "WORDS" VALUES('dick');
INSERT INTO "WORDS" VALUES('doekoe');
INSERT INTO "WORDS" VALUES('cola');
INSERT INTO "WORDS" VALUES('gvd');
INSERT INTO "WORDS" VALUES('jelly');
INSERT INTO "WORDS" VALUES('mad');
INSERT INTO "WORDS" VALUES('jemig');
INSERT INTO "WORDS" VALUES('rage');
INSERT INTO "WORDS" VALUES('rustig');
INSERT INTO "WORDS" VALUES('biatch');
INSERT INTO "WORDS" VALUES('cuck');
INSERT INTO "WORDS" VALUES('kalm');
INSERT INTO "WORDS" VALUES('nicor');
INSERT INTO "WORDS" VALUES('moeder');
INSERT INTO "WORDS" VALUES('cocksucker');
INSERT INTO "WORDS" VALUES('geketst');
INSERT INTO "WORDS" VALUES('vera');
INSERT INTO "WORDS" VALUES('ben');
INSERT INTO "WORDS" VALUES('van');
INSERT INTO "WORDS" VALUES('n00b');
INSERT INTO "WORDS" VALUES('mooi');
INSERT INTO "WORDS" VALUES('plee');
INSERT INTO "WORDS" VALUES('scheetje');
INSERT INTO "WORDS" VALUES('heb');
INSERT INTO "WORDS" VALUES('koekoek');
INSERT INTO "WORDS" VALUES('test');
INSERT INTO "WORDS" VALUES('kuthoer');
INSERT INTO "WORDS" VALUES('cocksuckerij');
INSERT INTO "WORDS" VALUES('euh');
INSERT INTO "WORDS" VALUES('factuur');
INSERT INTO "WORDS" VALUES('beta');

INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('1','1')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('1','1')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('1','1')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('1','2')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('1','3')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('1','3')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('1','3')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('2','1')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('2','2')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('3','3')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('4','3')
INSERT INTO WORDCOUNTS (USER_ID, WORD_ID) VALUES('3','3')

INSERT INTO WORDEMOJIS (WORD_ID,EMOJI_ID, USER_ID) VALUES('1','1','1')
INSERT INTO WORDEMOJIS (WORD_ID,EMOJI_ID, USER_ID) VALUES('1','2','1')
INSERT INTO WORDEMOJIS (WORD_ID,EMOJI_ID, USER_ID) VALUES('1','3','1')
INSERT INTO WORDEMOJIS (WORD_ID,EMOJI_ID, USER_ID) VALUES('2','1','1')
INSERT INTO WORDEMOJIS (WORD_ID,EMOJI_ID, USER_ID) VALUES('4','4','1')
INSERT INTO WORDEMOJIS (WORD_ID,EMOJI_ID, USER_ID) VALUES('5','4','1')

INSERT INTO HISTORY (USER_ID, MESSAGE, SLACK_TIMESTAMP, DATE_ADDED) VALUES ('1','dit is een test','1538387464.000100','2018-10-01 12:01:11')
INSERT INTO HISTORY (USER_ID, MESSAGE, SLACK_TIMESTAMP, DATE_ADDED) VALUES ('1','dit is een test2','1538387464.000100','2018-10-01 12:01:13')
INSERT INTO HISTORY (USER_ID, MESSAGE, SLACK_TIMESTAMP, DATE_ADDED) VALUES ('1','dit is een test3','1538387464.000100','2018-10-01 12:01:19')*/